name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          lfs: true   # ⬅️ Aktifkan LFS saat checkout

      # Install Git LFS
      - name: Install Git LFS
        run: |
          git lfs install

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env
      - name: Check Env
        run: echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run MLflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # Track large file types (sekali saja cukup)
      - name: Track model.pkl with Git LFS
        run: |
          git lfs track "*.pkl"
          git add .gitattributes

      # Commit and push results
      - name: Save mlruns to repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # atau pakai PAT jika perlu
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git add mlruns/ .gitattributes
          git commit -m "Save mlruns from CI run with LFS" || echo "Nothing to commit"
          git push origin main
